apiVersion: v1
kind: Service
metadata:
    name: docker-k8s-service
    labels:
      name: docker-k8s-service
spec:
  ports:
    - port: 8080
      nodePort: 30000
      targetPort: 8080
      protocol: TCP
  selector:
    app: dockerk8s
  type: LoadBalancer
  externalIPs:
    - 192.168.0.10
